service: build-gh-pages # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6

functions:
  build_docs:
    handler: handler.build_docs

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
