service: build-gh-pages

provider:
  name: aws
  runtime: python3.6
  timeout: 200
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    github_token: ${ssm:github_webhook_token}

functions:
  build_docs:
    handler: handler.build_docs
    events:
      - http:
          path: build_docs
          method: post
          cors: true
  build:
    handler: handler.build

plugins:
  - serverless-python-requirements

custom:
  serverlessSecrets:
    providerOptions:
      region: us-east-1
    keys:
      default: "alias/build_docs_conda"
  pythonRequirements:
    dockerizePip: non-linux
