service: build-gh-pages

provider:
  name: aws
  runtime: python3.6
  timeout: 200
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    github_token: ${self:custom.secrets.github_token}

functions:
  build_docs:
    handler: handler.build_docs
    events:
      - http:
          path: build_docs
          method: post
          cors: true
  build:
    handler: handler.build

plugins:
  - serverless-python-requirements

custom:
  secrets: ${file(secrets.json)}
  pythonRequirements:
    dockerizePip: non-linux
